// This file is auto-generated by Convex during development.
// In a real project, this would be generated automatically.

import { ConvexError } from "convex/values"

/**
 * A type representing a Convex query function.
 */
export type Query<Args extends unknown[], Output> = {
  args: Args
  _returnType: Output
}

/**
 * A type representing a Convex mutation function.
 */
export type Mutation<Args extends unknown[], Output> = {
  args: Args
  _returnType: Output
}

/**
 * Define a Convex query function.
 *
 * @param options - The query function and its options.
 * @returns The query function descriptor.
 */
export function query<Args extends unknown[], Output>(options: {
  args?: Record<string, any>
  handler: (ctx: any, ...args: Args) => Promise<Output> | Output
}): Query<Args, Output> {
  return {
    args: [] as unknown as Args,
    _returnType: null as unknown as Output,
  }
}

/**
 * Define a Convex mutation function.
 *
 * @param options - The mutation function and its options.
 * @returns The mutation function descriptor.
 */
export function mutation<Args extends unknown[], Output>(options: {
  args?: Record<string, any>
  handler: (ctx: any, ...args: Args) => Promise<Output> | Output
}): Mutation<Args, Output> {
  return {
    args: [] as unknown as Args,
    _returnType: null as unknown as Output,
  }
}

/**
 * Throw this error to indicate that the requested resource was not found.
 */
export function httpError(statusCode: number, message: string): never {
  throw new ConvexError(message)
}

